# -*- coding: utf-8 -*-
"""PYTHON CIA3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OfgeFpfGoCYGt-cgfh0wcCuTGUD863YP
"""

import pandas as pd

# Shortlisting Function
def shortlist(applicant):
    edu = applicant["education"]
    exp = applicant["experience"]
    score = applicant["test_score"]
    cert = applicant["certifications"]
    interview = applicant["interview_score"]
    location = applicant["location"]
    notice = applicant["notice_period"]

    if (edu == "MBA" or edu == "B.Tech") and exp >= 2 and score >= 60:
        if "Data Analytics" in cert or "Digital Marketing" in cert:
            if interview >= 70 and location.lower() == "delhi" and notice <= 30:
                return True
    return False

# Taking Input
applicants = []
n = int(input("Enter number of applicants: "))

for i in range(n):
    print(f"\nEnter details for applicant {i+1}:")
    name = input("Name: ")
    education = input("Education (MBA/B.Tech/Other): ")
    experience = int(input("Years of Experience: "))
    test_score = int(input("Test Score (out of 100): "))
    certifications = input("Enter certifications (comma separated): ")
    interview_score = int(input("Interview Score (out of 100): "))
    location = input("Preferred Job Location: ")
    notice_period = int(input("Notice Period (in days): "))

    applicant = {
        "name": name,
        "education": education,
        "experience": experience,
        "test_score": test_score,
        "certifications": certifications,
        "interview_score": interview_score,
        "location": location,
        "notice_period": notice_period
    }
    applicants.append(applicant)

# Applying Shortlisting
print("\n--- Shortlisting Results ---")
for applicant in applicants:
    if shortlist(applicant):
        print(applicant['name'], "→ Shortlisted")
    else:
        print(applicant['name'], "→ Not Shortlisted")

# Pandas Integration
df = pd.DataFrame(applicants)
print("\nDataFrame of All Applicants:")
print(df)

# Drop Example
df.drop("notice_period", axis=1, inplace=True)
print("\nAfter Dropping 'notice_period' Column:")
print(df)

# Filter Example
print("\nApplicants having 'Data Analytics' Certification:")
print(df[df["certifications"].str.contains("Data Analytics")])

# Series Example
print("\nEducation Column as Series:")
print(pd.Series(df["education"]))